version: "3"
services:
  datn-backend:
    container_name: datn-backend
    image: datn-backend
    build: .
    ports:
      - "8086:3000"
    volumes:
      - .:/home/node/backend
      - /home/node/backend/node_modules
    stdin_open: true
    tty: true
    environment:
      HOST: 0.0.0.0
    networks:
      - datn_recruitment_net
networks:
  datn_recruitment_net:
    external: true