version: "3"
name: datn-redis-stack

services:
  datn-redis:
    container_name: datn-redis
    image: redis:7.0
    restart: on-failure:3
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --user
      - default
      - "off"
      - --user
      - datn_admin
      - "on"
      - ">datn_123456"
      - "~*"
      - "+@all"
    ports:
      - "6380:6379"
    volumes:
      - ./data:/data
    networks:
      - datn_recruitment_net

networks:
  datn_recruitment_net:
    external: true